### ISSUE TITLE
Command-line convenience arguments?

### ISSUE THREAD

**Issue by mxmilkiib** [Lawrence-Chiappelli/screendimmer#10]
`screendimmer` works great as a tray menu for both internal and external screens, but other solutions like brillo don't manage that well.

Could it be possible to have the ability to use `screendimmer` from the command-line with arguments that get passed to the running process?

Maybe that's beyond the project scope, but I just thought it would be nice to have the same app do both, and maybe it would help keep the app stay in sync with the brightness status (because it hasn't been changed by another app).

Thanks again!

**Comment by Lawrence-Chiappelli** [comment]
> Could it be possible to have the ability to use screendimmer from the command-line with arguments that get passed to the running process?

Yeah. This would be more inclusive for command line users.

The project is more or less a glorified `xrandr` wrapper, so a temporary solution is `xrandr --output $monitor --brightness $brightness_value` and achieve the same results as the app.

Granted, I'm not positive if it will update dynamically in the tray. But there's a good chance it might refresh if you close/re-open it after entering that xrandr command. Command line args would be more ideal, though.

> Maybe that's beyond the project scope

I need to re-evaluate the scope of the project and the branding. I have considered command line users and standard, non-tray windows. The "tray" was convenient for the sake of development time, but after some thinking / reading others' feedback I can't think of a reason not to support other workflows.

Thank you for the feedback
