### ISSUE TITLE
Mousewheel on icon to change brightness up/down?

### ISSUE THREAD

**Issue by mxmilkiib** [Lawrence-Chiappelli/screendimmer#6]
I've been [thinking](https://github.com/jack-mixer/jack_mixer/issues/17) about mousewheels on tray icons, and I thought it would be a good suggestion for screendimmer.

**Comment by Lawrence-Chiappelli** [comment]
Agreed. The newest release has this implemented in the window itself - however I had not considered directly on the tray icon itself. I'll look into doing that.

As far as mousewheeling is concerned, feel free to check out what I have thus far:
![preview](https://user-images.githubusercontent.com/37488155/212212439-594c7a4c-4731-4085-b19c-5c06dc29c5ca.gif)

EDIT: should also mention the newest release is still a work in progress and available for contribution on [this branch](https://github.com/Lawrence-Chiappelli/screendimmer/tree/screendimmer-rewrite). Currently working on tying up loose-ends after taking an extended break from this project.
