### ISSUE TITLE
[Enhancement] Option to set brightness to 100% on exit/on turn off

### ISSUE THREAD

**Issue by T-3B** [Lawrence-Chiappelli/screendimmer#9]
I would love to have an option to set the brightness back at normal (100%) on application exit, so the next time we run `screendimmer` it doesn't change the brightness until we ask it explicitly.

I have it running automatically on my computer (Arch Linux), and the evening/night I set the brightness (from `screendimmer` tray icon) to 30%.
The problem is when I turn on my computer the morning, since I can barely see the screen.

In *my* case, normal brightness level (100%) reset at the app exit would be the easiest (instead of manually setting it to 100% during the night).

Thank you for considering this request for enhancement.

**Comment by Lawrence-Chiappelli** [comment]
> I would love to have an option to set the brightness back at normal (100%) on application exit

An upcoming update will support this, and is implemented.

> and the evening/night I set the brightness ... when I turn on my computer the morning, since I can barely see the screen.

This is a very valid corner case. Maybe I'll consider including time-based brightness adjustments in a future release. But the 100% brightness on exit is a great solution for this for now.

Thank you for the feedback.
